spring:
    security:
        ignored: "/actuator/**"

keycloak:
    url: http://localhost:8181
    realm: test
    jwk: ${keycloak.url}/realms/${keycloak.realm}/protocol/openid-connect/certs

entraid:
    tenant: 0
    jwk: https://login.microsoftonline.com/${entraid.tenant}/discovery/v2.0/keys
    issuer: https://login.microsoftonline.com/${entraid.tenant}/v2.0

server:
    port: 8082