spring:
    security:
        ignored: "/actuator/**"
#docker run --name postgreebanco -e POSTGRES_PASSWORD=123456 -d -p 5423:5432 postgres
    datasource:
        url: jdbc:postgresql://localhost:5423/eateasy
        username: dev
        password: 123456
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
          ddl-auto: update
        show-sql: true
        properties:
          hibernate:
            '[format_sql]': true
        database: postgresql
        database-plataform: org.hibernate.dialect.PostgreSQLDialect

keycloak:
    url: http://localhost:8181
    realm: test
    jwk: ${keycloak.url}/realms/${keycloak.realm}/protocol/openid-connect/certs

entraid:
    tenant: 0
    jwk: https://login.microsoftonline.com/${entraid.tenant}/discovery/v2.0/keys
    issuer: https://login.microsoftonline.com/${entraid.tenant}/v2.0

server:
    port: 8082